=== anigbojohnson/AgileCloudAutomationAssignment/Retake_Agile_Cloud_Automation/target/classes/currency_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "description": "A list of currency data including code, exchange rate to USD, country, and continent.",
  "items": {
    "type": "object",
    "description": "Currency information",
    "properties": {
      "code": {
        "type": "string",
        "description": "Represents the currency code of the target currency. This is represented in a string data type."
      },
      "rate_to_usd": {
        "type": "number",
        "description": "Indicates the conversion rate from USD to the respective currency. This is represented in double."
      },
      "country": {
        "type": "string",
        "description": "Indicates the country associated with the currency. This is represented in string data type."
      },
      "continent": {
        "type": "string",
        "description": "Represents the continent to which the currency belongs. This is represented in string datatype.",
        "enum": ["Africa", "Asia", "Europe", "North America", "South America", "Australia", "Worldwide"]
      }
    },
    "required": ["code", "rate_to_usd", "country", "continent"]
  }
}

=== anigbojohnson/AgileCloudAutomationAssignment/Retake_Agile_Cloud_Automation/src/main/resources/currency.json
[
    {
        "code": "USD",
        "rate_to_usd": 1,
        "country": "United States of America",
        "continent": "North America"
    },
    {
        "code": "AED",
        "rate_to_usd": 3.67,
        "country": "United Arab Emirates",
        "continent": "Asia"
    },
    {
        "code": "AFN",
        "rate_to_usd": 70.89,
        "country": "Afghanistan",
        "continent": "Asia"
    },
    {
        "code": "ALL",
        "rate_to_usd": 95.26,
        "country": "Albania",
        "continent": "Europe"
    },
    {
        "code": "AMD",
        "rate_to_usd": 405.5,
        "country": "Armenia",
        "continent": "Asia"
    },
    {
        "code": "ANG",
        "rate_to_usd": 1.79,
        "country": "Netherlands Antilles",
        "continent": "North America"
    },
    {
        "code": "AOA",
        "rate_to_usd": 841.97,
        "country": "Angola",
        "continent": "Africa"
    },
    {
        "code": "ARS",
        "rate_to_usd": 816.05,
        "country": "Argentina",
        "continent": "South America"
    },
    {
        "code": "AUD",
        "rate_to_usd": 1.49,
        "country": "Australia",
        "continent": "Australia"
    },
    {
        "code": "AWG",
        "rate_to_usd": 1.79,
        "country": "Aruba",
        "continent": "North America"
    },
    {
        "code": "AZN",
        "rate_to_usd": 1.7,
        "country": "Azerbaijan",
        "continent": "Asia"
    },
    {
        "code": "BAM",
        "rate_to_usd": 1.79,
        "country": "Bosnia and Herzegovina",
        "continent": "Europe"
    },
    {
        "code": "BBD",
        "rate_to_usd": 2,
        "country": "Barbados",
        "continent": "North America"
    },
    {
        "code": "BDT",
        "rate_to_usd": 109.56,
        "country": "Bangladesh",
        "continent": "Asia"
    },
    {
        "code": "BGN",
        "rate_to_usd": 2.28,
        "country": "Bulgaria",
        "continent": "Europe"
    },
    {
        "code": "BHD",
        "rate_to_usd": 0.479,
        "country": "Bahrain",
        "continent": "Asia"
    },
    {
        "code": "BIF",
        "rate_to_usd": 3630.48,
        "country": "Burundi",
        "continent": "Africa"
    },
    {
        "code": "BMD",
        "rate_to_usd": 1.27,
        "country": "Bermuda",
        "continent": "North America"
    },
    {
        "code": "BND",
        "rate_to_usd": 1.7,
        "country": "Brunei Darussalam",
        "continent": "Asia"
    },
    {
        "code": "BOB",
        "rate_to_usd": 8.75,
        "country": "Bolivia",
        "continent": "South America"
    },
    {
        "code": "BRL",
        "rate_to_usd": 6.2,
        "country": "Brazil",
        "continent": "South America"
    },
    {
        "code": "BSD",
        "rate_to_usd": 1.27,
        "country": "Bahamas",
        "continent": "North America"
    },
    {
        "code": "BTN",
        "rate_to_usd": 105.68,
        "country": "Bhutan",
        "continent": "Asia"
    },
    {
        "code": "BWP",
        "rate_to_usd": 17.33,
        "country": "Botswana",
        "continent": "Africa"
    },
    {
        "code": "BYN",
        "rate_to_usd": 4.1,
        "country": "Belarus",
        "continent": "Europe"
    },
    {
        "code": "BZD",
        "rate_to_usd": 2.55,
        "country": "Belize",
        "continent": "North America"
    },
    {
        "code": "CAD",
        "rate_to_usd": 1.71,
        "country": "Canada",
        "continent": "North America"
    },
    {
        "code": "CDF",
        "rate_to_usd": 3500.82,
        "country": "Democratic Republic of the Congo",
        "continent": "Africa"
    },
    {
        "code": "CHF",
        "rate_to_usd": 1.09,
        "country": "Switzerland",
        "continent": "Europe"
    },
    {
        "code": "CLP",
        "rate_to_usd": 1161.45,
        "country": "Chile",
        "continent": "South America"
    },
    {
        "code": "CNY",
        "rate_to_usd": 9.15,
        "country": "China",
        "continent": "Asia"
    },
    {
        "code": "COP",
        "rate_to_usd": 5059.9,
        "country": "Colombia",
        "continent": "South America"
    },
    {
        "code": "CRC",
        "rate_to_usd": 661.3,
        "country": "Costa Rica",
        "continent": "North America"
    },
    {
        "code": "CUP",
        "rate_to_usd": 30.6,
        "country": "Cuba",
        "continent": "North America"
    },
    {
        "code": "CVE",
        "rate_to_usd": 128.34,
        "country": "Cape Verde",
        "continent": "Africa"
    },
    {
        "code": "CZK",
        "rate_to_usd": 28.69,
        "country": "Czech Republic",
        "continent": "Europe"
    },
    {
        "code": "DJF",
        "rate_to_usd": 226.59,
        "country": "Djibouti",
        "continent": "Africa"
    },
    {
        "code": "DKK",
        "rate_to_usd": 8.68,
        "country": "Denmark",
        "continent": "Europe"
    },
    {
        "code": "DOP",
        "rate_to_usd": 73.44,
        "country": "Dominican Republic",
        "continent": "North America"
    },
    {
        "code": "DZD",
        "rate_to_usd": 170.68,
        "country": "Algeria",
        "continent": "Africa"
    },
    {
        "code": "EGP",
        "rate_to_usd": 39.3,
        "country": "Egypt",
        "continent": "Africa"
    },
    {
        "code": "ERN",
        "rate_to_usd": 19.12,
        "country": "Eritrea",
        "continent": "Africa"
    },
    {
        "code": "ETB",
        "rate_to_usd": 70.22,
        "country": "Ethiopia",
        "continent": "Africa"
    },
    {
        "code": "EUR",
        "rate_to_usd": 1.16,
        "country": "Eurozone",
        "continent": "Europe"
    },
    {
        "code": "FJD",
        "rate_to_usd": 2.82,
        "country": "Fiji",
        "continent": "Australia"
    },
    {
        "code": "FKP",
        "rate_to_usd": 1,
        "country": "Falkland Islands",
        "continent": "South America"
    },
    {
        "code": "FOK",
        "rate_to_usd": 8.68,
        "country": "Faroe Islands",
        "continent": "Europe"
    },
    {
        "code": "GEL",
        "rate_to_usd": 3.41,
        "country": "Georgia",
        "continent": "Asia"
    },
    {
        "code": "GGP",
        "rate_to_usd": 1,
        "country": "Guernsey",
        "continent": "Europe"
    },
    {
        "code": "GHS",
        "rate_to_usd": 15.37,
        "country": "Ghana",
        "continent": "Africa"
    },
    {
        "code": "GIP",
        "rate_to_usd": 1,
        "country": "Gibraltar",
        "continent": "Europe"
    },
    {
        "code": "GMD",
        "rate_to_usd": 81.92,
        "country": "Gambia",
        "continent": "Africa"
    },
    {
        "code": "GNF",
        "rate_to_usd": 10946.17,
        "country": "Guinea",
        "continent": "Africa"
    },
    {
        "code": "GTQ",
        "rate_to_usd": 9.88,
        "country": "Guatemala",
        "continent": "North America"
    },
    {
        "code": "GYD",
        "rate_to_usd": 267.09,
        "country": "Guyana",
        "continent": "South America"
    },
    {
        "code": "HKD",
        "rate_to_usd": 9.97,
        "country": "Hong Kong",
        "continent": "Asia"
    },
    {
        "code": "HNL",
        "rate_to_usd": 31.16,
        "country": "Honduras",
        "continent": "North America"
    },
    {
        "code": "HRK",
        "rate_to_usd": 8.77,
        "country": "Croatia",
        "continent": "Europe"
    },
    {
        "code": "HTG",
        "rate_to_usd": 169.81,
        "country": "Haiti",
        "continent": "North America"
    },
    {
        "code": "HUF",
        "rate_to_usd": 441.07,
        "country": "Hungary",
        "continent": "Europe"
    },
    {
        "code": "IDR",
        "rate_to_usd": 19829.54,
        "country": "Indonesia",
        "continent": "Asia"
    },
    {
        "code": "ILS",
        "rate_to_usd": 4.76,
        "country": "Israel",
        "continent": "Asia"
    },
    {
        "code": "IMP",
        "rate_to_usd": 1,
        "country": "Isle of Man",
        "continent": "Europe"
    },
    {
        "code": "INR",
        "rate_to_usd": 105.68,
        "country": "India",
        "continent": "Asia"
    },
    {
        "code": "IQD",
        "rate_to_usd": 1675.61,
        "country": "Iraq",
        "continent": "Asia"
    },
    {
        "code": "IRR",
        "rate_to_usd": 53785.84,
        "country": "Iran",
        "continent": "Asia"
    },
    {
        "code": "ISK",
        "rate_to_usd": 174.75,
        "country": "Iceland",
        "continent": "Europe"
    },
    {
        "code": "JEP",
        "rate_to_usd": 1,
        "country": "Jersey",
        "continent": "Europe"
    },
    {
        "code": "JMD",
        "rate_to_usd": 196.88,
        "country": "Jamaica",
        "continent": "North America"
    },
    {
        "code": "JOD",
        "rate_to_usd": 0.904,
        "country": "Jordan",
        "continent": "Asia"
    },
    {
        "code": "JPY",
        "rate_to_usd": 184.79,
        "country": "Japan",
        "continent": "Asia"
    },
    {
        "code": "KES",
        "rate_to_usd": 202.8,
        "country": "Kenya",
        "continent": "Africa"
    },
    {
        "code": "KGS",
        "rate_to_usd": 113.86,
        "country": "Kyrgyzstan",
        "continent": "Asia"
    },
    {
        "code": "KHR",
        "rate_to_usd": 5227.89,
        "country": "Cambodia",
        "continent": "Asia"
    },
    {
        "code": "KID",
        "rate_to_usd": 1.91,
        "country": "Kiribati",
        "continent": "Australia"
    },
    {
        "code": "KMF",
        "rate_to_usd": 572.61,
        "country": "Comoros",
        "continent": "Africa"
    },
    {
        "code": "KRW",
        "rate_to_usd": 1672.72,
        "country": "South Korea",
        "continent": "Asia"
    },
    {
        "code": "KWD",
        "rate_to_usd": 0.39,
